import 'package:mockito/mockito.dart';
import 'package:sample/features/todo/data/todo_repository.dart';

// Mock of TodoRepository generated by Mockito.
class MockTodoRepository extends Mock implements TodoRepository {}
